# Generated by Django 4.1.7 on 2023-04-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='удалено'),
        ),
    ]
