# Generated by Django 4.1.7 on 2023-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_is_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_employer',
            field=models.BooleanField(verbose_name='работодатель'),
        ),
    ]
